name: 'Oilmod Testrail uploader'
description: 'Upload junit test results to testrail'
inputs:
  testrail-user: # id of input
    description: 'Testrail username'
    required: true
  testrail-host:
    description: 'URL to testrail api'
    required: false
    default: https://oiltradeent.testrail.io
  testrail-password:
    description: 'Testrail password'
    required: true
  path-to-files:
    description: 'Path to folder containing xml files'
    required: true
  testrail-project:
    description: 'Testrail project name'
    required: true
  testrail-run-title:
    description: 'Testrail run title'
    required: false
    default: 'Automated tests'
  testrail-suite-id:
    description: 'Testrail test suite ID. If not provided and you dont provide suite-name, testrail generates a new suite pr run'
    required: false
  suite-name:
    description: 'Name of suite to create / append to in testrail'
    required: false
  run-reference:
    description: 'URL to pull request, job or just text detailing the run'
    required: false
    default: 'No external reference added'
  close:
    description: 'Close run'
    required: false
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - run: pip install trcli
      shell: bash
    - uses: actions/setup-node@v2
      shell: bash
      run: npm install -g merge-junit-suites
    - shell: bash
      run: merge-junit-suites merge --path ${{ inputs.path-to-files }} --name ${{ inputs.suite-name }} --output ${{ inputs.path-to-files }}/junit-report.xml
    - run: |
        ARGS=""
        RUNARGS=""
        if [ -n "$SUITE" ]; then ARGS="$ARGS --suite-id $SUITE"; fi;
        if [ -n "$CLOSE" ]; then RUNARGS="$RUNARGS --close-run"; fi;
        trcli -y \
          -h "$HOST" \
          --project "$PROJECT" \
          --username "$USER" \
          --password "$PASSWORD" \
          $ARGS \
          parse_junit \
          -f "$JUNITPATH/junit-report.xml" \
          --title "$TITLE" \
          --run-description "$REFERENCE" \
          $RUNARGS
      shell: bash
      env:
        REFERENCE: ${{ inputs.run-reference }}
        SUITE: ${{ inputs.testrail-suite-id }}
        CLOSE: ${{ inputs.close }}
        HOST: ${{ inputs.testrail-host }}
        PROJECT: ${{ inputs.testrail-project }}
        USER: ${{ inputs.testrail-user }}
        PASSWORD: ${{ inputs.testrail-password }}
        JUNITPATH: ${{ inputs.path-to-files }}
        TITLE: ${{ inputs.testrail-run-title }}
    - run: echo "[Testrail suite](https://oiltradeent.testrail.net/index.php?/suites/runs/$SUITE)" >> $GITHUB_STEP_SUMMARY
      env:
        SUITE: ${{ inputs.testrail-suite-id }}
      shell: bash
